from enum import Enum


class SessionEndReason(Enum):
    UPPER_LIMIT_REACHED = "UPPER_LIMIT_REACHED"
    LOWER_LIMIT_REACHED = "LOWER_LIMIT_REACHED"
    MANUAL = "MANUAL"
    TIMEOUT = "TIMEOUT"
    MAX_GAMES_REACHED = "MAX_GAMES_REACHED"